# Generated by Django 4.2.3 on 2023-07-14 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country_name', models.CharField(max_length=50, unique=True, verbose_name='اسم الدولة')),
            ],
            options={
                'verbose_name': 'الدولة',
                'verbose_name_plural': 'الدول',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city_name', models.CharField(max_length=50, unique=True, verbose_name='اسم المدينة')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
            ],
            options={
                'verbose_name': 'المدينة',
                'verbose_name_plural': 'المدن',
            },
        ),
    ]
