# Generated by Django 4.2.3 on 2023-09-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(choices=[('IRAQ', 'العراق'), ('TURKEY', 'تركيا'), ('EGYPT', 'مصر'), ('SAUDI_ARABIA', 'السعودية'), ('UNITED_ARAB_EMIRATES', 'الامارات العربية المتحدة'), ('SYRIA', 'سوريا'), ('LEBANON', 'لبنان'), ('IRAN', 'ايران'), ('TUNISIA', 'تونس'), ('OMAN', 'عمان'), ('MALAYSIA', 'ماليزيا'), ('GEORGIA', 'جورجيا'), ('AZERBAIJAN', 'اذربيجان'), ('ARMENIA', 'ارمينيا'), ('SRILANKA', 'سيريلانكا'), ('INDONESIA', 'اندونيسيا')], default='IRAQ', max_length=50, unique=True, verbose_name='اسم الدولة'),
        ),
    ]
