# Generated by Django 4.2.3 on 2023-08-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='merchant_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء العضوية'),
        ),
    ]
