# Generated by Django 4.2.3 on 2023-07-21 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2023, 7, 21, 0, 1, 55, 555442, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='الاسم الاول'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2023, 7, 21, 0, 1, 58, 316192, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='الاسم الثاني'),
            preserve_default=False,
        ),
    ]
