# Generated by Django 4.2.3 on 2023-07-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_emailaccount_image_profileuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='image',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='الصورة'),
        ),
    ]
