# Generated by Django 4.2.3 on 2023-09-04 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_emailaccount_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='android_link',
            field=models.CharField(default=datetime.datetime(2023, 9, 4, 22, 23, 25, 991381, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='رابط التطبيق للاندرويد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appdetails',
            name='ios_link',
            field=models.CharField(default=datetime.datetime(2023, 9, 4, 22, 23, 34, 96229, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='رابط التطبيق للايفون'),
            preserve_default=False,
        ),
    ]
