# Generated by Django 4.2.1 on 2023-07-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
