# Generated by Django 4.2.3 on 2023-07-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profileuser_image_emailaccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
