# Generated by Django 4.2.3 on 2023-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_appdetails_android_link_appdetails_ios_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_deleter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
