# Generated by Django 4.2.3 on 2023-07-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profileuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
