# Generated by Django 4.2.3 on 2023-07-30 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_emailaccount_created_emailaccount_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
