# Generated by Django 4.2.3 on 2023-07-30 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profileuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app_version', models.CharField(max_length=100, verbose_name='رقم الاصدار التطبيق')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
