# Generated by Django 4.2.3 on 2023-07-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_appdetails'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailaccount',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='type',
            field=models.CharField(choices=[('normal', 'عادي'), ('merchant', 'تاجر')], default='normal', max_length=10, verbose_name='النوع'),
        ),
    ]
