# Generated by Django 4.2.3 on 2023-07-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_emailaccount_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantUser',
            fields=[
            ],
            options={
                'verbose_name': 'تاجر',
                'verbose_name_plural': 'التجار',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.emailaccount',),
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
            ],
            options={
                'verbose_name': 'مستخدم عادي',
                'verbose_name_plural': 'المستخدمين العاديين',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.emailaccount',),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_normal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
