# Generated by Django 4.2.3 on 2023-08-01 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merchantuser_normaluser_emailaccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.normaluser'),
        ),
        migrations.CreateModel(
            name='ProfileMerchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.merchantuser')),
            ],
            options={
                'verbose_name': 'الملف الشخصي ',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
