# Generated by Django 4.2.3 on 2023-08-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profileuser_user_profilemerchant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
