# Generated by Django 4.2.3 on 2023-08-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_delete_profileuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_merchant',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_normal',
        ),
    ]
