# Generated by Django 4.2.3 on 2023-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_emailaccount_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
