# Generated by Django 4.2.3 on 2023-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_emailaccount_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_normal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
