# Generated by Django 4.2.3 on 2023-08-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_emailaccount_is_merchant_emailaccount_is_normal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_merchant',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_normal',
        ),
    ]
