# Generated by Django 4.2.3 on 2023-08-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profilemerchant_options_profilenormal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_normal',
        ),
    ]
