# Generated by Django 4.2.3 on 2023-08-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_emailaccount_is_normal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='type',
        ),
    ]
