# Generated by Django 4.2.3 on 2023-08-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_emailaccount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='is_merchant',
        ),
    ]
