# Generated by Django 4.2.3 on 2023-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_emailaccount_is_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemerchant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profilenormal',
            name='user',
        ),
        migrations.DeleteModel(
            name='MerchantUser',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProfileMerchant',
        ),
        migrations.DeleteModel(
            name='ProfileNormal',
        ),
    ]
