# Generated by Django 4.2.3 on 2023-08-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_remove_placemixin_merchant_placemixin_user'),
        ('account', '0025_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
