# Generated by Django 4.2.3 on 2023-07-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceMixin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('place_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل المكان')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('short_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='الموقع')),
                ('location', location_field.models.plain.PlainLocationField(blank=True, default='33.3152, 44.3661', max_length=63, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
            ],
            options={
                'verbose_name': 'كافيه',
                'verbose_name_plural': 'كافيهات',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
            ],
            options={
                'verbose_name': ' مكان ترفيهي',
                'verbose_name_plural': 'اماكن ترفيهية',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
                ('type', models.CharField(choices=[('بنك', 'بنك'), ('Atm', 'ATM'), ('صرافة', 'صرافة')], max_length=50, verbose_name='نوع المكان')),
            ],
            options={
                'verbose_name': 'الخدمة المالية',
                'verbose_name_plural': 'الخدمات المالية',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
            ],
            options={
                'verbose_name': 'محطة وقود',
                'verbose_name_plural': 'محطات وقود',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
            ],
            options={
                'verbose_name': 'مكان رياضي',
                'verbose_name_plural': 'اماكن رياضية',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='HealthCentre',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
                ('type', models.CharField(choices=[('مستشفى', 'مستشفى'), ('عيادة', 'عيادة'), ('صيدلية', 'صيدلية')], max_length=50, verbose_name='نوع المركز')),
            ],
            options={
                'verbose_name': 'مركز صحي',
                'verbose_name_plural': 'مراكز صحية',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='HolyPlace',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
                ('type', models.CharField(choices=[('مسجد', 'مسجد'), ('كنيسة', 'كنيسة'), ('ضريح', 'ضريح')], max_length=50, verbose_name='نوع المكان')),
            ],
            options={
                'verbose_name': 'مكان مقدس',
                'verbose_name_plural': 'أماكن مقدسة',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
            ],
            options={
                'verbose_name': 'مول',
                'verbose_name_plural': 'مولات',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
            ],
            options={
                'verbose_name': 'مطعم',
                'verbose_name_plural': 'مطاعم',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
                ('type', models.CharField(choices=[('حلاق رجالي', 'حلاق رجالي'), ('صالون نسائي', 'صالون نسائي')], max_length=50, verbose_name='نوع المكان')),
            ],
            options={
                'verbose_name': 'حلاقة وصالون',
                'verbose_name_plural': 'حلاقة وصالونات',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='StayPlace',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
                ('type', models.CharField(choices=[('فندق', 'فندق'), ('شقق', 'شقق'), ('مزرعة', 'مزرعة')], default='فندق', max_length=50, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'مكان اقامة',
                'verbose_name_plural': 'اماكن اقامة',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('placemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.placemixin')),
                ('type', models.CharField(choices=[('اماكن سياحية', (('مصيف', 'مصيف'), ('متحف', 'متحف'), ('شلال', 'شلال'))), ('اماكن عامة', (('منتزه', 'منتزه'), ('متحف', 'متحف'), ('معلم حضاري', 'معلم حضاري')))], max_length=50, verbose_name='نوع المكان')),
            ],
            options={
                'verbose_name': 'مكان سياحي',
                'verbose_name_plural': 'أماكن سياحية',
            },
            bases=('place.placemixin',),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='انستجرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تليجرام')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='واتساب')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='place.placemixin')),
            ],
            options={
                'verbose_name': 'وسائل التواصل الاجتماعي',
                'verbose_name_plural': 'وسائل التواصل الاجتماعي',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('rating', models.IntegerField(default=0, verbose_name='التقييم')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'تعليقات',
            },
        ),
        migrations.CreateModel(
            name='RecommendedPlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country', verbose_name='الدولة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'مكان موصى به',
                'verbose_name_plural': 'اماكن موصى بها',
            },
        ),
        migrations.CreateModel(
            name='LatestPlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country', verbose_name='الدولة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'احدث الاماكن',
                'verbose_name_plural': 'احدث الاماكن',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/', verbose_name='الصورة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.placemixin')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'صور',
            },
        ),
        migrations.CreateModel(
            name='FavoritePlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to='place.placemixin', verbose_name='المكان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مكان مفضل',
                'verbose_name_plural': 'اماكن مفضلة',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='advertisements', verbose_name='الصورة')),
                ('title', models.CharField(max_length=50, verbose_name='العنوان')),
                ('short_description', models.CharField(max_length=100, verbose_name='الوصف المختصر')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='الرابط')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المكان')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country', verbose_name='الدولة')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'الاعلانات',
            },
        ),
    ]
