# Generated by Django 4.2.3 on 2023-08-17 20:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50, verbose_name='اسم الشركة')),
                ('image', models.ImageField(upload_to='company', verbose_name='الصورة')),
                ('company_description', models.CharField(max_length=100, verbose_name='وصف الشركة')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='location.city', verbose_name='المدينة')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='location.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='PlaceMixin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('short_location', models.CharField(max_length=50, verbose_name='الموقع')),
                ('location', location_field.models.plain.PlainLocationField(default='33.3152, 44.3661', max_length=63)),
                ('price', models.FloatField(blank=True, max_length=50, null=True, verbose_name='السعر')),
                ('open', models.CharField(blank=True, max_length=50, null=True, verbose_name='المتاح')),
                ('is_archived', models.BooleanField(default=False, verbose_name='تم الأرشفة')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_places', to='location.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('restaurant', 'مطعم'), ('stayplace', 'مكان اقامة'), ('cafe', 'مقهى'), ('touristplace', 'مكان سياحي'), ('mall', 'مول'), ('healthcenter', 'مركز صحي'), ('holyplace', 'مكان مقدس'), ('financial', 'مالي'), ('gasstation', 'محطة وقود'), ('entertainment', 'ترفيهي'), ('sport', 'رياضي'), ('salons', 'صالونات')], max_length=50, verbose_name='الاسم')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('short_description', models.CharField(max_length=100, verbose_name='الوصف المختصر')),
                ('trip_name', models.CharField(max_length=50, verbose_name='اسم الرحلة')),
                ('trip_details', models.TextField(max_length=256, verbose_name='تفاصيل الرحلة')),
                ('location', location_field.models.plain.PlainLocationField(default='33.3152, 44.3661', max_length=63, verbose_name='موقع الشركة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_details', to='place.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'تفاصيل الرحلة',
                'verbose_name_plural': 'تفاصيل الرحلات',
            },
        ),
        migrations.CreateModel(
            name='TripSocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='فيسبوك')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='انستغرام')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='تليجرام')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='واتساب')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_social_media', to='place.tripdetails', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'وسائل التواصل الاجتماعي',
                'verbose_name_plural': 'وسائل التواصل الاجتماعي',
            },
        ),
        migrations.CreateModel(
            name='TripImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='trip_images', verbose_name='الصورة')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_image', to='place.tripdetails', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'صورة الرحلة',
                'verbose_name_plural': 'صور الرحلات',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='فيسبوك')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='انستغرام')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='تليجرام')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='واتساب')),
                ('place', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='place.placemixin')),
            ],
            options={
                'verbose_name': 'وسائل التواصل الاجتماعي',
                'verbose_name_plural': 'وسائل التواصل الاجتماعي',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('rating', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('reported', models.BooleanField(default=False, verbose_name='تم الابلاغ')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'تعليقات',
            },
        ),
        migrations.CreateModel(
            name='RecommendedPlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_places', to='location.country', verbose_name='الدولة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'مكان موصى به',
                'verbose_name_plural': 'اماكن موصى بها',
            },
        ),
        migrations.CreateModel(
            name='PlaceSubType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_type_sub_types', to='place.placetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='placemixin',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='place.placetype'),
        ),
        migrations.AddField(
            model_name='placemixin',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_sub_type_places', to='place.placesubtype'),
        ),
        migrations.AddField(
            model_name='placemixin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='offers', verbose_name='الصورة')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='الرابط')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='location.country', verbose_name='الدولة')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
            },
        ),
        migrations.CreateModel(
            name='LatestPlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_places', to='location.city', verbose_name='المدينة')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_places', to='location.country', verbose_name='الدولة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'احدث الاماكن',
                'verbose_name_plural': 'احدث الاماكن',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/', verbose_name='الصورة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.placemixin')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'صور',
            },
        ),
        migrations.CreateModel(
            name='FavoritePlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to='place.placemixin', verbose_name='المكان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مكان مفضل',
                'verbose_name_plural': 'اماكن مفضلة',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='advertisements', verbose_name='الصورة')),
                ('title', models.CharField(max_length=50, verbose_name='العنوان')),
                ('short_description', models.CharField(max_length=100, verbose_name='الوصف المختصر')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='الرابط')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='location.city', verbose_name='المدينة')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='location.country', verbose_name='الدولة')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'الاعلانات',
            },
        ),
    ]
