# Generated by Django 4.2.3 on 2023-08-06 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetype',
            name='tn_ancestors_count',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_ancestors_pks',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_children_count',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_children_pks',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_depth',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_descendants_count',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_descendants_pks',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_index',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_level',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_order',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_parent',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_priority',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_siblings_count',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='tn_siblings_pks',
        ),
        migrations.CreateModel(
            name='PlaceSubType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_type_sub_types', to='place.placetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='placemixin',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_sub_type_places', to='place.placesubtype'),
        ),
    ]
