# Generated by Django 4.2.1 on 2023-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemixin',
            name='place_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل المكان'),
        ),
        migrations.AddField(
            model_name='placemixin',
            name='short_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الموقع'),
        ),
    ]
