# Generated by Django 4.2.3 on 2023-07-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='place',
        ),
    ]
