# Generated by Django 4.2.3 on 2023-07-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_country'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='location.country', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='latestplaces',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_places', to='location.country', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='recommendedplaces',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_places', to='location.country', verbose_name='الدولة'),
        ),
    ]
