# Generated by Django 4.2.3 on 2023-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemixin',
            name='place_details',
        ),
        migrations.AlterField(
            model_name='placemixin',
            name='description',
            field=models.TextField(default=1, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placemixin',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placemixin',
            name='short_location',
            field=models.CharField(default=1, max_length=50, verbose_name='الموقع'),
            preserve_default=False,
        ),
    ]
