# Generated by Django 4.2.3 on 2023-08-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_placetype_tn_ancestors_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placemixin',
            options={'verbose_name': 'مكان', 'verbose_name_plural': 'اماكن'},
        ),
        migrations.AlterField(
            model_name='placemixin',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='place.placetype'),
        ),
        migrations.AddIndex(
            model_name='placemixin',
            index=models.Index(fields=['location'], name='place_place_locatio_d538b4_idx'),
        ),
    ]
