# Generated by Django 4.2.3 on 2023-07-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('place', '0002_remove_advertisement_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='المكان'),
        ),
    ]
