# Generated by Django 4.2.3 on 2023-07-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_country'),
        ('place', '0002_alter_advertisement_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemixin',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_places', to='location.city'),
        ),
    ]
