# Generated by Django 4.2.1 on 2023-07-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_placemixin_place_details_placemixin_short_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemixin',
            name='contact_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الاتصال'),
        ),
        migrations.AlterField(
            model_name='stayplace',
            name='type',
            field=models.CharField(choices=[('فندق', 'فندق'), ('شقق', 'شقق'), ('مزرعة', 'مزرعة')], default='فندق', max_length=50, verbose_name='نوع'),
        ),
    ]
