# Generated by Django 4.2.3 on 2023-07-27 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_company_offers_trip_tripdetails_delete_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='trip_days',
            field=models.CharField(default=datetime.datetime(2023, 7, 27, 4, 12, 55, 363861, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='عدد ايام الرحلة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='trip_details',
            field=models.CharField(default=datetime.datetime(2023, 7, 27, 4, 13, 2, 435695, tzinfo=datetime.timezone.utc), max_length=256, verbose_name='تفاصيل الرحلة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='trip_price',
            field=models.CharField(default=datetime.datetime(2023, 7, 27, 4, 13, 10, 27282, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='سعر الرحلة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='trip_type',
            field=models.CharField(choices=[('Family', 'عائلة'), ('Friends', 'اصدقاء')], default='Family', max_length=50, verbose_name='نوع الرحلة'),
            preserve_default=False,
        ),
    ]
