# Generated by Django 4.2.3 on 2023-07-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0002_alter_favoriteplaces_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteplaces',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to='place.placemixin', verbose_name='المكان'),
        ),
        migrations.AlterField(
            model_name='favoriteplaces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
