# Generated by Django 4.2.1 on 2023-07-06 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_placemixin_contact_details_alter_stayplace_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('فيسبوك', 'فيسبوك'), ('تويتر', 'تويتر'), ('انستجرام', 'انستجرام'), ('تيك توك', 'تيك توك'), ('يوتيوب', 'يوتيوب'), ('سناب شات', 'سناب شات'), ('موقع الكتروني', 'موقع الكتروني')], default='فيسبوك', max_length=50, verbose_name='نوع')),
                ('link', models.URLField(verbose_name='الرابط')),
            ],
            options={
                'verbose_name': 'موقع تواصل اجتماعي',
                'verbose_name_plural': 'مواقع التواصل الاجتماعي',
            },
        ),
        migrations.AddField(
            model_name='placemixin',
            name='social_media',
            field=models.ManyToManyField(blank=True, null=True, to='place.socialmedia', verbose_name='مواقع التواصل الاجتماعي'),
        ),
    ]
