# Generated by Django 4.2.3 on 2023-07-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_tripdetails_trip_days_tripdetails_trip_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_details',
            field=models.TextField(max_length=256, verbose_name='تفاصيل الرحلة'),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_type',
            field=models.CharField(choices=[('Family', 'عائلة'), ('youth', 'شباب')], max_length=50, verbose_name='نوع الرحلة'),
        ),
    ]
