# Generated by Django 4.2.3 on 2023-08-22 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_tripdetails_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='فيسبوك')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='انستغرام')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='تليجرام')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='واتساب')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_social', to='place.company', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'وسائل التواصل الاجتماعي',
                'verbose_name_plural': 'وسائل التواصل الاجتماعي',
            },
        ),
        migrations.DeleteModel(
            name='TripSocialMedia',
        ),
    ]
