# Generated by Django 4.2.3 on 2023-07-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('place', '0003_remove_advertisement_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location.country', verbose_name='الدولة'),
            preserve_default=False,
        ),
    ]
