# Generated by Django 4.2.3 on 2023-08-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_advertisement_country_alter_placetype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placemixin',
            old_name='type',
            new_name='sub_type',
        ),
    ]
