# Generated by Django 4.2.3 on 2023-07-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_socialmedia_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reported',
            field=models.BooleanField(default=False, verbose_name='تم الابلاغ'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='فيسبوك'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انستغرام'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تليجرام'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='واتساب'),
        ),
    ]
