# Generated by Django 4.2.3 on 2023-07-10 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('place', '0004_advertisement_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='المكان'),
        ),
        migrations.CreateModel(
            name='RecommendedPlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'مكان موصى به',
                'verbose_name_plural': 'اماكن موصى بها',
            },
        ),
        migrations.CreateModel(
            name='LatestPlaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'احدث الاماكن',
                'verbose_name_plural': 'احدث الاماكن',
            },
        ),
    ]
