# Generated by Django 4.2.3 on 2023-08-26 09:21

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_companysocialmedia_delete_tripsocialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='location',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='33.3152, 44.3661', max_length=63, verbose_name='موقع الشركة'),
        ),
        migrations.AlterField(
            model_name='companysocialmedia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='place.company', verbose_name='الشركة '),
        ),
    ]
