# Generated by Django 4.2.1 on 2023-07-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_socialmedia_placemixin_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemixin',
            name='social_media',
        ),
        migrations.AddField(
            model_name='placemixin',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='placemixin',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='انستجرام'),
        ),
        migrations.AddField(
            model_name='placemixin',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='تليجرام'),
        ),
        migrations.AddField(
            model_name='placemixin',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='تويتر'),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
