# Generated by Django 4.2.1 on 2023-07-06 22:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_remove_placemixin_social_media_placemixin_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='انستجرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تليجرام')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='واتساب')),
            ],
            options={
                'verbose_name': 'وسائل التواصل الاجتماعي',
                'verbose_name_plural': 'وسائل التواصل الاجتماعي',
            },
        ),
        migrations.RemoveField(
            model_name='placemixin',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='placemixin',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='placemixin',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='placemixin',
            name='twitter',
        ),
        migrations.AddField(
            model_name='placemixin',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.socialmedia'),
        ),
    ]
