# Generated by Django 4.2.3 on 2023-07-30 08:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_tripdetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='فيسبوك')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='انستغرام')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='تليجرام')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='واتساب')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_social_media', to='place.tripdetails', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'وسائل التواصل الاجتماعي',
                'verbose_name_plural': 'وسائل التواصل الاجتماعي',
            },
        ),
        migrations.CreateModel(
            name='TripImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='trip_images', verbose_name='الصورة')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_image', to='place.tripdetails', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'صورة الرحلة',
                'verbose_name_plural': 'صور الرحلات',
            },
        ),
    ]
