# Generated by Django 4.2.3 on 2023-07-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_advertisement_content_type_recommendedplaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.placemixin', verbose_name='المكان'),
        ),
    ]
