# Generated by Django 4.2.3 on 2023-07-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_reviews_reported_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayplace',
            name='type',
            field=models.CharField(choices=[('Hotel', 'فندق'), ('flat', 'شقق'), ('farm', 'مزرعة')], default='Hotel', max_length=50, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='type',
            field=models.CharField(choices=[('resort', 'مصيف'), ('museum', 'متحف'), ('waterfall', 'شلال'), ('park', 'منتزه'), ('heritage', 'معلم حضاري')], max_length=50, verbose_name='نوع المكان'),
        ),
    ]
