# Generated by Django 4.2.3 on 2023-08-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_rename_type_placemixin_sub_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placemixin',
            old_name='sub_type',
            new_name='type',
        ),
    ]
