# Generated by Django 4.2.1 on 2023-07-06 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_socialmedia_remove_placemixin_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='انستجرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تليجرام')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='واتساب')),
            ],
            options={
                'verbose_name': 'وسائل التواصل الاجتماعي',
                'verbose_name_plural': 'وسائل التواصل الاجتماعي',
            },
        ),
        migrations.RemoveField(
            model_name='placemixin',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='placemixin',
            name='social_media',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.AddField(
            model_name='contact',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin'),
        ),
    ]
