# Generated by Django 4.2.3 on 2023-07-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_stayplace_type_alter_touristplace_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='type',
            field=models.CharField(choices=[('Bank', 'بنك'), ('Atm', 'ATM'), ('Exchange', 'صرافة')], max_length=50, verbose_name='نوع المكان'),
        ),
        migrations.AlterField(
            model_name='healthcentre',
            name='type',
            field=models.CharField(choices=[('Hospital', 'مستشفى'), ('Clinic', 'عيادة'), ('Pharmacy', 'صيدلية')], max_length=50, verbose_name='نوع المركز'),
        ),
        migrations.AlterField(
            model_name='holyplace',
            name='type',
            field=models.CharField(choices=[('Mosque', 'مسجد'), ('Church', 'كنيسة'), ('Shrine', 'ضريح')], max_length=50, verbose_name='نوع المكان'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='type',
            field=models.CharField(choices=[('barber', 'حلاق رجالي'), ('salon', 'صالون نسائي')], max_length=50, verbose_name='نوع المكان'),
        ),
    ]
