# Generated by Django 4.2.3 on 2023-07-30 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_tripsocialmedia_tripimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='company_description',
        ),
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.CharField(default=datetime.datetime(2023, 7, 30, 8, 16, 8, 871968, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='وصف الشركة'),
            preserve_default=False,
        ),
    ]
