# Generated by Django 4.2.3 on 2023-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_rename_sub_type_placemixin_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placemixin',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='placemixin',
            name='place_place_locatio_d538b4_idx',
        ),
    ]
