# Generated by Django 4.2.3 on 2023-07-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_remove_trip_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemixin',
            name='price',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='السعر'),
        ),
    ]
