# Generated by Django 4.2.1 on 2023-07-06 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_contact_remove_placemixin_contact_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.placemixin'),
        ),
    ]
