# Generated by Django 4.2.3 on 2023-08-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_placemixin_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='title',
        ),
    ]
