# Generated by Django 4.2.3 on 2023-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_alter_placemixin_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthCentre',
            new_name='HealthCenter',
        ),
        migrations.AlterField(
            model_name='sport',
            name='type',
            field=models.CharField(choices=[('Gym', 'نادي رياضي'), ('gaming', 'صالة العاب')], max_length=50, verbose_name='نوع المكان'),
        ),
    ]
