# Generated by Django 4.2.3 on 2023-08-01 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0010_rename_healthcentre_healthcenter_alter_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemixin',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
