# Generated by Django 4.2.3 on 2023-09-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_alter_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_company', to='place.company'),
        ),
        migrations.DeleteModel(
            name='CompanySocialMedia',
        ),
    ]
