# Generated by Django 4.2.3 on 2023-08-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_merchant'),
        ('place', '0011_placemixin_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemixin',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_places', to='account.merchant'),
        ),
    ]
