# Generated by Django 4.2.3 on 2023-09-02 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_socialmedia_company_delete_companysocialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.company'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.placemixin'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='place.company'),
        ),
        migrations.DeleteModel(
            name='ReviewsCompany',
        ),
    ]
