# Generated by Django 4.2.3 on 2023-07-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
    ]
