# Generated by Django 4.2.3 on 2023-09-03 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_reviews_company_alter_reviews_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='entity_type',
            field=models.CharField(choices=[('place', 'Place'), ('company', 'Company')], default=datetime.datetime(2023, 9, 3, 3, 44, 4, 281075, tzinfo=datetime.timezone.utc), max_length=10, verbose_name='Entity Type'),
            preserve_default=False,
        ),
    ]
