# Generated by Django 4.2.3 on 2023-08-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_alter_placemixin_merchant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placemixin',
            options={'permissions': [('add_place', 'Can add place'), ('edit_place', 'Can edit place')]},
        ),
    ]
