# Generated by Django 4.2.3 on 2023-09-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_reviews_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_company', to='place.company'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media', to='place.placemixin'),
        ),
    ]
