# Generated by Django 4.2.3 on 2023-08-02 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0014_alter_placemixin_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemixin',
            name='merchant',
        ),
        migrations.AddField(
            model_name='placemixin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
