# Generated by Django 4.2.3 on 2023-07-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
    ]
