# Generated by Django 4.2.3 on 2023-07-07 01:02

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('place', '0016_alter_advertisement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='location.city'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='location.country'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
    ]
