# Generated by Django 4.2.3 on 2023-10-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_advertisement_short_description_advertisement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemixin',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_type', to='place.placetype'),
        ),
    ]
