# Generated by Django 4.2.3 on 2023-07-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('place', '0017_advertisement_city_advertisement_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='place',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='object_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
