# Generated by Django 4.2.3 on 2023-10-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0017_alter_placemixin_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.CharField(max_length=1000, verbose_name='وصف الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_details',
            field=models.TextField(max_length=5000, verbose_name='تفاصيل الرحلة'),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_name',
            field=models.CharField(max_length=100, verbose_name='اسم الرحلة'),
        ),
    ]
