# Generated by Django 4.2.3 on 2023-07-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0019_remove_advertisement_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'الاعلانات'},
        ),
    ]
